engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true

# Exclude test directories
exclude_paths:
  - test/**

ratings:
  paths:
    - lib/**
    - "**.js"
